
package br.edu.ftlf.ads.revenda.webservice.impl;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RevendaServices", targetNamespace = "http://impl.webservice.revenda.ads.ftlf.edu.br/", wsdlLocation = "META-INF/wsdl/RevendaServices.wsdl")
public class RevendaServices_Service
    extends Service
{

    private final static URL REVENDASERVICES_WSDL_LOCATION;
    private final static WebServiceException REVENDASERVICES_EXCEPTION;
    private final static QName REVENDASERVICES_QNAME = new QName("http://impl.webservice.revenda.ads.ftlf.edu.br/", "RevendaServices");

    static {
        REVENDASERVICES_WSDL_LOCATION = br.edu.ftlf.ads.revenda.webservice.impl.RevendaServices_Service.class.getClassLoader().getResource("META-INF/wsdl/RevendaServices.wsdl");
        WebServiceException e = null;
        if (REVENDASERVICES_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'META-INF/wsdl/RevendaServices.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        REVENDASERVICES_EXCEPTION = e;
    }

    public RevendaServices_Service() {
        super(__getWsdlLocation(), REVENDASERVICES_QNAME);
    }

    public RevendaServices_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), REVENDASERVICES_QNAME, features);
    }

    public RevendaServices_Service(URL wsdlLocation) {
        super(wsdlLocation, REVENDASERVICES_QNAME);
    }

    public RevendaServices_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, REVENDASERVICES_QNAME, features);
    }

    public RevendaServices_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RevendaServices_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RevendaServices
     */
    @WebEndpoint(name = "RevendaServicesPort")
    public RevendaServices getRevendaServicesPort() {
        return super.getPort(new QName("http://impl.webservice.revenda.ads.ftlf.edu.br/", "RevendaServicesPort"), RevendaServices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RevendaServices
     */
    @WebEndpoint(name = "RevendaServicesPort")
    public RevendaServices getRevendaServicesPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.webservice.revenda.ads.ftlf.edu.br/", "RevendaServicesPort"), RevendaServices.class, features);
    }

    private static URL __getWsdlLocation() {
        if (REVENDASERVICES_EXCEPTION!= null) {
            throw REVENDASERVICES_EXCEPTION;
        }
        return REVENDASERVICES_WSDL_LOCATION;
    }

}
